config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :workers
  get 'project_details/new', to: 'project_details#new'
  post 'project_details', to: 'project_details#create'
  delete 'project_details/:id', to: 'project_details#destroy', as: 'pd_delete'
  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_details, dependent: :destroy
  has_many :workers, through: :project_details

end

app/models/project_detail.rb
class ProjectDetail < ApplicationRecord
  belongs_to :worker
  belongs_to :project
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :project_details, dependent: :destroy
  has_many :projects, through: :project_details


  def project_worker (project)
    project_details.find_by(project_id: project.id).id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/project_details_controller.rb
class ProjectDetailsController < ApplicationController

  def new
    @project_detail = ProjectDetail.new
  end

  def create
    @project_detail = ProjectDetail.new(project_params)
    @project_detail.save
    redirect_to projects_path
  end

  def destroy
    @project_detail = ProjectDetail.find(params[:id])
    @project_detail.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project_detail).permit(:project_id, :worker_id)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @all_workers = @project.workers
  end


  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
    @all_projects = @worker.projects
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_details_helper.rb
module ProjectDetailsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item <%= 'active' if current_page?(workers_path) %>">
        <%= link_to 'Workers', workers_path, class:'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(projects_path) %>">
        <%= link_to 'Projects', projects_path, class:'nav-link' %>
      </li>
      <div class="nav-item <%= 'active' if current_page?(project_details_new_path) %>">
        <%= link_to 'Add Worker to Projects',project_details_new_path , class:'nav-link' %>
      </div>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PreparaciNPruebaNan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/project_details/new.html.erb
<h1>Add Worker to Projects</h1>
<p>Select the worker and the project you want to assign to him, then press 'Add Worker'</p>
<p>You can see every project assigned to workers in project's show page</p>

<%= form_with(model: @project_detail, local:true) do |f| %>

  <%= f.label :worker_id %>
  <%= f.select :worker_id, Worker.pluck(:name, :email, :id), id: :worker_project_id, prompt: "Select Worker"%>
  <br>
  <%= f.label :project_id %>
  <%= f.select :project_id, Project.pluck(:name, :description, :id), id: :project_worker_id, prompt: "Select Project" %>
  <br>
  <%= f.submit 'Add worker' %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class=" text-center">Projects</h1>

<%= link_to 'New Project', new_project_path, class: 'btn btn-success col-sm-12' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>

        <td>
          <div class="dropdown float-right">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to 'Show', project, class:'dropdown-item' %>
              <%= link_to 'Edit', edit_project_path(project), class:'dropdown-item' %>
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class:'dropdown-item' %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<h2> Workers</h2>
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
<% @all_workers.each do |worker| %>
  <tr>
    <td><%= worker.name %></td>
    <td><%= worker.email %></td>
    <td><%= link_to 'Eliminar trabajador', pd_delete_path(worker.project_worker(@project)), method: :delete  %></td>
  </tr>
<% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/workers/_form.html.erb
<%= form_with(model: worker, local: true) do |form| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class=" text-center">Workers</h1>
<%= link_to 'New Worker', new_worker_path, class: 'btn btn-success col-sm-12'  %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <td><%= worker.email %></td>
        <td>
        <div class="dropdown float-right">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <%= link_to 'Show', worker, class:'dropdown-item' %>
            <%= link_to 'Edit', edit_worker_path(worker), class:'dropdown-item' %>
            <%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' }, class:'dropdown-item' %>
          </div>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @worker.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @worker.email %>
</p>

<h2> Projects</h2>
<table class="table">
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
  <% @all_projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= link_to 'Eliminar proyecto', pd_delete_path(@worker.project_worker(project)), method: :delete  %></td>
    </tr>
  <% end %>
    </tbody>
</table>
<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>